title: "Feature Request - Please use our Public Roadmap"
labels:
  - redirect
body:
  - type: markdown
    attributes:
      value: |
        **Feature requests have moved to our Public Roadmap**
        
        Please submit your request here: https://roadmap.directus.io/roadmap
        
        This allows you to:
        - ✅ Vote on features you'd like to see
        - 📊 See what we're currently working on
        - 📅 See what is planned
        - 🎯 Track feature status in real-time, directly integrated with our Linear projects
        
        **Not a feature request?** If you'd like to engage with our community, ask questions, or get help, please visit: https://community.directus.io

  - type: textarea
    id: note
    attributes:
      label: "Quick note (optional)"
      description: "This discussion will be auto-closed. Please visit roadmap.directus.io to submit your feature request!"
    validations:
      required: false
