title: "Feature Request - Please use our Public Roadmap"
labels:
  - redirect
body:
  - type: markdown
    attributes:
      value: |
        **Feature requests have moved to our public roadmap.**
        
        Please submit your request here: https://roadmap.directus.io/roadmap
        
        This allows you to:
        - ✅ Vote on features you'd like to see
        - 📊 See what we're currently working on
        - 📅 See what is planned
        - 🎯 Track feature status in real-time, directly integrated with our Linear projects
        
        **Steps:**
        1. Visit the roadmap
        2. Search if your idea already exists
        3. If it exists, upvote it and provide additional feedback on the subject
        3. If it's new, submit your feature request there
        
        This discussion will be automatically closed. Thank you!

  - type: checkboxes
    id: acknowledge
    attributes:
      label: "Acknowledgment"
      options:
        - label: "I understand feature requests should be submitted at roadmap.directus.io"
          required: true
