title: "Feature Request - Please use our Public Roadmap"
labels:
  - redirect
body:
  - type: markdown
    attributes:
      value: >-
        # 🚀 Feature Requests Have Moved!
      
        We've moved feature requests to our dedicated roadmap platform for better tracking and community voting. 
        
        ## Please submit your feature request here:
        ### **[https://roadmap.directus.io/roadmap](https://roadmap.directus.io/roadmap)**
        
        ---
        
        ## Why the change?
        - ✅ Continue to vote on features you'd like to see
        - 📊 See what we're currently working on
        - 📅 See what is planned
        - 🎯 Track feature status in real-time, directly integrated with our Linear projects
        
        ## What to do:
        1. Visit [roadmap.directus.io/roadmap](https://roadmap.directus.io/roadmap)
        2. Search to see if your idea already exists
        3. If it exists, upvote it and provide additional feedback on the subject!
        4. If it's new, submit your feature request there
        
        ---
        
        **This GitHub discussion will be automatically closed.** Thank you for understanding!

  - type: checkboxes
    id: acknowledge
    attributes:
      label: "Acknowledgment"
      options:
        - label: "I understand feature requests should be submitted at roadmap.directus.io"
          required: true
